"""Dense spatial Zernike coefficient field used by D3.

The experiment-level invariants are intentionally simple:

* Noll modes j=2..231 use exactly the same point covariance as D2;
* the spatial field is generated by a stationary FFT sampler;
* one fixed geometry, TILT_CORR_HALF_PX=55, is used for the spatial
  correlation so no second physical axis is introduced;
* at every output pixel, before the same 4-sigma tilt clipping as D2,

      Cov[a(p)] = C_Noll * (D/r0)^(5/3).

For runtime reasons the stationary Gaussian field is drawn on a regular
anchor grid and bilinearly interpolated.  Bilinear interpolation changes the
variance between anchors, so a deterministic variance map removes that purely
numerical modulation.  Because every latent mode uses the same spatial
correlation, the same scalar correction restores the complete Noll covariance,
not only the diagonal variances.

Array convention matches ``Kolmogorov.coeffs``: index 0 is Noll j=2,
index 1 is j=3, ..., index 229 is j=231.  Piston is omitted.
"""

from functools import lru_cache

import numpy as np
import scipy.fft as sfft
from scipy.integrate import quad
from scipy.special import jv

from .wavefront import K_MODES, noll_cov

TILT_CORR_HALF_PX = 55.0
# Numerical sampling density only.  It is not a turbulence parameter.
ANCHOR_SPACING_PX = 4.0


def _bessel_int(order, s):
    return quad(
        lambda z: z ** (-14.0 / 3.0)
        * jv(order, 2.0 * s * z)
        * jv(2, z) ** 2,
        0.0,
        1e3,
        limit=2000,
    )[0]


@lru_cache(maxsize=1)
def corr_table():
    """Normalized tilt correlation C(s) used by the previous D3 geometry."""
    s = np.concatenate(
        [np.linspace(0.0, 5.0, 101), np.geomspace(5.25, 220.0, 80)]
    )
    i0 = np.array([_bessel_int(0, v) for v in s], dtype=np.float64)
    i2 = np.array([_bessel_int(2, v) for v in s], dtype=np.float64)
    c = (i0 + i2) / i0[0]
    c[0] = 1.0
    return s, c


def _cov_blocks(cov, tol=1e-14):
    """Connected sparse blocks of the Noll covariance matrix."""
    adjacency = np.abs(cov) > tol
    seen = np.zeros(len(cov), dtype=bool)
    groups = []
    for start in range(len(cov)):
        if seen[start]:
            continue
        stack = [start]
        seen[start] = True
        group = []
        while stack:
            u = stack.pop()
            group.append(u)
            for v in np.flatnonzero(adjacency[u]):
                v = int(v)
                if not seen[v]:
                    seen[v] = True
                    stack.append(v)
        groups.append(np.asarray(sorted(group), dtype=np.intp))
    return groups


def _rfft_full_sum(a):
    """Sum a real-even spectrum represented by rfft2 over the full FFT."""
    if a.shape[-1] == 1:
        return float(a[..., 0].sum())
    # For even FFT length, first and last rfft columns are self-conjugate.
    return float(a[..., 0].sum() + a[..., -1].sum() + 2.0 * a[..., 1:-1].sum())


def _bilinear_resize(x, n):
    """Resize (C,g,g) -> (C,n,n) by bilinear interpolation."""
    x = np.asarray(x, dtype=np.float32)
    c, g, g2 = x.shape
    if g != g2:
        raise ValueError("anchor field must be square")
    n = int(n)
    if g == n:
        return x
    if g == 1:
        return np.broadcast_to(x, (c, n, n)).astype(np.float32, copy=True)

    q = np.linspace(0.0, g - 1.0, n, dtype=np.float32)
    i0 = np.floor(q).astype(np.intp)
    i1 = np.minimum(i0 + 1, g - 1)
    t = q - i0

    y = x[:, i0, :] * (1.0 - t)[None, :, None] + x[:, i1, :] * t[None, :, None]
    return (
        y[:, :, i0] * (1.0 - t)[None, None, :]
        + y[:, :, i1] * t[None, None, :]
    ).astype(np.float32, copy=False)


class DenseZernikeSampler:
    """Stationary FFT sampler for modes j=2..K with D2/Noll marginals."""

    def __init__(
        self,
        k_modes=K_MODES,
        corr_half_px=TILT_CORR_HALF_PX,
        anchor_spacing_px=ANCHOR_SPACING_PX,
    ):
        self.k_modes = int(k_modes)
        self.corr_half_px = float(corr_half_px)
        self.anchor_spacing_px = float(anchor_spacing_px)
        if self.k_modes != K_MODES:
            raise ValueError(f"D3 is fixed at K_MODES={K_MODES}")
        if self.corr_half_px <= 0.0 or self.anchor_spacing_px <= 0.0:
            raise ValueError("spatial scales must be positive")

        # Exactly the same point covariance as D2, piston removed.
        self.cov = noll_cov(self.k_modes)[1:, 1:].astype(np.float64, copy=False)
        self.groups = _cov_blocks(self.cov)
        self.block_roots = []
        for idx in self.groups:
            sub = self.cov[np.ix_(idx, idx)]
            self.block_roots.append(np.linalg.cholesky(sub).astype(np.float32))

        self.s_tab, self.c_tab = corr_table()
        s_half = np.interp(0.5, self.c_tab[::-1], self.s_tab[::-1])
        self.px_per_s = self.corr_half_px / float(s_half)

        self._geom_cache = {}
        self._root_cache = {}
        self._var_cache = {}

    @property
    def n_coeff(self):
        return self.k_modes - 1

    def modal_covariance_from_roots(self):
        """Reconstruct C_Noll from the block Cholesky factors."""
        out = np.zeros_like(self.cov)
        for idx, root in zip(self.groups, self.block_roots):
            rr = root.astype(np.float64)
            out[np.ix_(idx, idx)] = rr @ rr.T
        return out

    def _geometry(self, n):
        n = int(n)
        cached = self._geom_cache.get(n)
        if cached is not None:
            return cached
        if n <= 1:
            g, step = 1, 1.0
        else:
            g = int(np.ceil((n - 1) / self.anchor_spacing_px)) + 1
            g = max(2, min(g, n))
            step = (n - 1) / (g - 1)
        self._geom_cache[n] = (g, float(step))
        return self._geom_cache[n]

    def _embed_size(self, n):
        """FFT-friendly circulant embedding size, always >= 2*g and even."""
        g, _ = self._geometry(n)
        return 2 * int(sfft.next_fast_len(g))

    def _spectrum_root(self, n):
        """Root spectrum of the unit-variance stationary latent field."""
        n = int(n)
        cached = self._root_cache.get(n)
        if cached is not None:
            return cached
        g, step = self._geometry(n)
        m = self._embed_size(n)
        lag = np.minimum(np.arange(m), m - np.arange(m)).astype(np.float64)
        radius_px = np.hypot(lag[:, None], lag[None, :]) * step
        cov = np.interp(
            radius_px / self.px_per_s,
            self.s_tab,
            self.c_tab,
            left=1.0,
            right=float(self.c_tab[-1]),
        )
        lam = np.maximum(sfft.rfft2(cov).real, 0.0)
        total = _rfft_full_sum(lam)
        if not np.isfinite(total) or total <= 0.0:
            raise RuntimeError("invalid D3 spatial spectrum")
        # numpy/scipy irfft2 divides by m^2, hence this normalization gives
        # exactly unit variance at every anchor point.
        root = np.sqrt(lam * (m * m / total)).astype(np.float32)
        self._root_cache[n] = root
        return root

    def embedded_corr(self, n):
        """Autocorrelation represented by the FFT embedding, for tests."""
        g, _ = self._geometry(n)
        m = self._embed_size(n)
        root = self._spectrum_root(n).astype(np.float64)
        cov = sfft.irfft2(root * root, s=(m, m)).real
        return cov / cov[0, 0]

    def _interp_variance(self, n):
        """Variance map produced by bilinear interpolation of a unit field."""
        n = int(n)
        cached = self._var_cache.get(n)
        if cached is not None:
            return cached
        g, _ = self._geometry(n)
        if g == n:
            v = np.ones((n, n), dtype=np.float32)
            self._var_cache[n] = v
            return v

        m = self._embed_size(n)
        root = self._spectrum_root(n).astype(np.float64)
        cov = sfft.irfft2(root * root, s=(m, m)).real
        c00 = float(cov[0, 0])
        cx = float(cov[0, 1] / c00)
        cy = float(cov[1, 0] / c00)
        cpp = float(cov[1, 1] / c00)
        cpm = float(cov[1, -1] / c00)

        q = np.linspace(0.0, g - 1.0, n, dtype=np.float64)
        f = q - np.floor(q)
        a = 1.0 - f
        b = f
        w00 = a[:, None] * a[None, :]
        w01 = a[:, None] * b[None, :]
        w10 = b[:, None] * a[None, :]
        w11 = b[:, None] * b[None, :]

        v = w00*w00 + w01*w01 + w10*w10 + w11*w11
        v += 2.0 * cx * (w00*w01 + w10*w11)
        v += 2.0 * cy * (w00*w10 + w01*w11)
        v += 2.0 * cpp * (w00*w11)
        v += 2.0 * cpm * (w01*w10)
        v = np.maximum(v, 1e-6).astype(np.float32)
        self._var_cache[n] = v
        return v

    def _draw_blocks_coarse(self, n, rng, group_ids):
        """Draw selected independent Noll blocks on the internal FFT grid.

        Used only for the two blocks containing j=2 and j=3 in production.
        Other independent blocks are marginalized directly to the PSF-anchor
        locations, so their unused dense spatial samples are never generated.
        """
        n = int(n)
        g, _ = self._geometry(n)
        m = self._embed_size(n)
        spectral_root = self._spectrum_root(n)
        out = {}
        for gi in group_ids:
            idx = self.groups[gi]
            modal_root = self.block_roots[gi]
            b = len(idx)
            white = rng.standard_normal((b, m, m), dtype=np.float32)
            spec = sfft.rfft2(white, axes=(-2, -1)) * spectral_root[None, :, :]
            latent = sfft.irfft2(spec, s=(m, m), axes=(-2, -1))[:, :g, :g]
            latent = latent.astype(np.float32, copy=False)
            mixed = modal_root @ latent.reshape(b, -1)
            out[gi] = mixed.reshape(b, g, g).astype(np.float32, copy=False)
        return out

    def _draw_mixed_coarse(self, n, rng):
        """Reference full-field construction retained for diagnostics/tests."""
        n = int(n)
        g, _ = self._geometry(n)
        m = self._embed_size(n)
        spectral_root = self._spectrum_root(n)
        mixed = np.empty((self.n_coeff, g, g), dtype=np.float32)
        for idx, modal_root in zip(self.groups, self.block_roots):
            b = len(idx)
            white = rng.standard_normal((b, m, m), dtype=np.float32)
            spec = sfft.rfft2(white, axes=(-2, -1)) * spectral_root[None, :, :]
            latent = sfft.irfft2(spec, s=(m, m), axes=(-2, -1))[:, :g, :g]
            latent = latent.astype(np.float32, copy=False)
            mixed[idx] = (modal_root @ latent.reshape(b, -1)).reshape(b, g, g)
        return mixed

    def _sample_regular_via_dense(self, coarse, n, out_g):
        """Match ``_bilinear_resize(..., n)`` + variance correction +
        regular sampling, without materializing the full dense coefficient
        stack.
        """
        coarse = np.asarray(coarse, dtype=np.float32)
        c, g, g2 = coarse.shape
        n, out_g = int(n), int(out_g)
        if g != g2 or n < 2 or out_g < 2:
            raise ValueError("invalid coarse/dense sampling geometry")

        qd = np.linspace(0.0, n - 1.0, out_g, dtype=np.float32)
        d0 = np.floor(qd).astype(np.intp)
        d1 = np.minimum(d0 + 1, n - 1)
        td = qd - d0
        ids = np.unique(np.concatenate([d0, d1]))

        qc = ids.astype(np.float32) * np.float32((g - 1) / (n - 1))
        c0 = np.floor(qc).astype(np.intp)
        c1 = np.minimum(c0 + 1, g - 1)
        tc = qc - c0
        y = (coarse[:, c0, :] * (1.0 - tc)[None, :, None]
             + coarse[:, c1, :] * tc[None, :, None])
        sub = (y[:, :, c0] * (1.0 - tc)[None, None, :]
               + y[:, :, c1] * tc[None, None, :])

        inv_std = 1.0 / np.sqrt(self._interp_variance(n))
        sub *= inv_std[np.ix_(ids, ids)][None, :, :]

        p0 = np.searchsorted(ids, d0)
        p1 = np.searchsorted(ids, d1)
        yy = sub[:, p0, :] * (1.0 - td)[None, :, None] + sub[:, p1, :] * td[None, :, None]
        return (
            yy[:, :, p0] * (1.0 - td)[None, None, :]
            + yy[:, :, p1] * td[None, None, :]
        ).astype(np.float32, copy=False)

    def _anchor_sparse_weights(self, n, out_g):
        """Sparse coarse-grid weights for the exact legacy anchor sampler.

        Returns one dict per output anchor.  Applying these weights to a
        coarse latent field is algebraically identical to
        ``_sample_regular_via_dense`` for a single channel.
        """
        n, out_g = int(n), int(out_g)
        g, _ = self._geometry(n)
        inv_std = 1.0 / np.sqrt(self._interp_variance(n))
        qd = np.linspace(0.0, n - 1.0, out_g, dtype=np.float64)

        anchors = []
        for ya in qd:
            y0 = int(np.floor(ya)); y1 = min(y0 + 1, n - 1); ty = ya - y0
            yd = ((y0, 1.0 - ty), (y1, ty))
            for xa in qd:
                x0 = int(np.floor(xa)); x1 = min(x0 + 1, n - 1); tx = xa - x0
                xd = ((x0, 1.0 - tx), (x1, tx))
                weights = {}
                for yy, wy in yd:
                    if wy == 0.0:
                        continue
                    qy = yy * (g - 1) / (n - 1)
                    cy0 = int(np.floor(qy)); cy1 = min(cy0 + 1, g - 1); fy = qy - cy0
                    yc = ((cy0, 1.0 - fy), (cy1, fy))
                    for xx, wx in xd:
                        if wx == 0.0:
                            continue
                        qx = xx * (g - 1) / (n - 1)
                        cx0 = int(np.floor(qx)); cx1 = min(cx0 + 1, g - 1); fx = qx - cx0
                        xc = ((cx0, 1.0 - fx), (cx1, fx))
                        outer = wy * wx * float(inv_std[yy, xx])
                        for cy, wcy in yc:
                            if wcy == 0.0:
                                continue
                            for cx, wcx in xc:
                                if wcx == 0.0:
                                    continue
                                key = (cy, cx)
                                weights[key] = weights.get(key, 0.0) + outer * wcy * wcx
                anchors.append(weights)
        return anchors

    def _anchor_spatial_root(self, n, out_g):
        """Spatial covariance root at PSF anchors under the legacy sampler.

        This is the exact Gaussian marginal of the previous FFT-field path at
        the only high-order locations D3 consumes.  Sampling from it therefore
        changes no distribution used by D3; it merely integrates out unused
        coarse/dense pixels for Noll blocks independent of tilt.
        """
        key = (int(n), int(out_g))
        cache = getattr(self, "_anchor_root_cache", None)
        if cache is None:
            self._anchor_root_cache = {}
            cache = self._anchor_root_cache
        if key in cache:
            return cache[key]

        n, out_g = key
        weights = self._anchor_sparse_weights(n, out_g)
        m = self._embed_size(n)
        root_fft = self._spectrum_root(n).astype(np.float64)
        cov = sfft.irfft2(root_fft * root_fft, s=(m, m)).real
        p = len(weights)
        k = np.empty((p, p), dtype=np.float64)
        for a, wa in enumerate(weights):
            for b in range(a + 1):
                wb = weights[b]
                val = 0.0
                for (ya, xa), va in wa.items():
                    for (yb, xb), vb in wb.items():
                        val += va * vb * cov[(ya - yb) % m, (xa - xb) % m]
                k[a, b] = k[b, a] = val

        # Numerical eig-root is robust to tiny roundoff negatives.  It
        # reproduces K to machine precision without adding a variance jitter.
        ev, vec = np.linalg.eigh(k)
        spatial_root = (vec * np.sqrt(np.maximum(ev, 0.0))).astype(np.float32)
        cache[key] = spatial_root
        return spatial_root

    def _tilt_group_ids(self):
        ids = []
        for gi, idx in enumerate(self.groups):
            if 0 in idx or 1 in idx:
                ids.append(gi)
        if len(ids) != 2:
            raise RuntimeError(f"expected two tilt-containing Noll blocks, got {ids}")
        return tuple(ids)

    def sample_for_d3_reference(self, n, d_over_r0, rng, high_grid):
        """Previous full-coarse path retained only for acceptance tests."""
        n = int(n); dr = float(d_over_r0); high_grid = int(high_grid)
        coarse = self._draw_mixed_coarse(n, rng)
        scale = np.float32(dr ** (5.0 / 6.0))
        tilt = _bilinear_resize(coarse[:2], n)
        tilt *= (1.0 / np.sqrt(self._interp_variance(n)))[None, :, :]
        tilt *= scale
        high = self._sample_regular_via_dense(coarse[2:], n, high_grid)
        high *= scale
        return tilt.astype(np.float32, copy=False), high.astype(np.float32, copy=False)

    def sample_for_d3(self, n, d_over_r0, rng, high_grid):
        """Draw only coefficient values actually consumed by D3.

        The two Noll blocks containing j=2,j=3 are still generated by the
        original FFT field, preserving their joint dense tilt/high-order
        statistics.  Every other Noll block is independent of tilt and is
        sampled directly from the exact Gaussian marginal at the PSF-anchor
        locations.  No physical/statistical approximation is introduced.
        """
        n = int(n); dr = float(d_over_r0); high_grid = int(high_grid)
        if n <= 0 or high_grid < 2:
            raise ValueError("invalid D3 sampling geometry")
        if not np.isfinite(dr) or dr <= 0.0:
            raise ValueError("d_over_r0 must be positive and finite")

        scale = np.float32(dr ** (5.0 / 6.0))
        tilt = np.empty((2, n, n), dtype=np.float32)
        high = np.empty((self.n_coeff - 2, high_grid, high_grid), dtype=np.float32)
        inv_std = (1.0 / np.sqrt(self._interp_variance(n))).astype(np.float32)

        tilt_gids = self._tilt_group_ids()
        coarse_blocks = self._draw_blocks_coarse(n, rng, tilt_gids)
        for gi in tilt_gids:
            idx = self.groups[gi]
            block = coarse_blocks[gi]
            # Dense output only for the actual tilt row in each block.
            for row, mode_idx in enumerate(idx):
                if mode_idx in (0, 1):
                    dense = _bilinear_resize(block[row:row+1], n)[0]
                    dense *= inv_std
                    tilt[mode_idx] = dense * scale
            # The high-order members of the same block are needed only at
            # PSF anchors, but must remain jointly realized with the tilt.
            sampled = self._sample_regular_via_dense(block, n, high_grid)
            for row, mode_idx in enumerate(idx):
                if mode_idx >= 2:
                    high[mode_idx - 2] = sampled[row] * scale

        spatial_root = self._anchor_spatial_root(n, high_grid)
        p = high_grid * high_grid
        tilt_set = set(tilt_gids)
        for gi, (idx, modal_root) in enumerate(zip(self.groups, self.block_roots)):
            if gi in tilt_set:
                continue
            b = len(idx)
            white = rng.standard_normal((b, p), dtype=np.float32)
            latent = white @ spatial_root.T
            mixed = modal_root @ latent
            for row, mode_idx in enumerate(idx):
                # All modes in non-tilt blocks are high-order.
                high[mode_idx - 2] = mixed[row].reshape(high_grid, high_grid) * scale

        return tilt, high

    def sample(self, n, d_over_r0, rng):
        """Draw all dense coefficients; diagnostic/reference API only."""
        n = int(n); dr = float(d_over_r0)
        if n <= 0 or not np.isfinite(dr) or dr <= 0.0:
            raise ValueError("invalid sampling arguments")
        coarse = self._draw_mixed_coarse(n, rng)
        out = _bilinear_resize(coarse, n)
        out *= (1.0 / np.sqrt(self._interp_variance(n)))[None, :, :]
        out *= np.float32(dr ** (5.0 / 6.0))
        return out.astype(np.float32, copy=False)
