"""Dense spatial Zernike coefficient field used by D3.

The experiment-level invariants are intentionally simple:

* Noll modes j=2..231 use exactly the same point covariance as D2;
* the spatial field is generated by a stationary FFT sampler;
* one fixed geometry, TILT_CORR_HALF_PX=55, is used for the spatial
  correlation so no second physical axis is introduced;
* at every output pixel, before the same 4-sigma tilt clipping as D2,

      Cov[a(p)] = C_Noll * (D/r0)^(5/3).

For runtime reasons the stationary Gaussian field is drawn on a regular
anchor grid and bilinearly interpolated.  Bilinear interpolation changes the
variance between anchors, so a deterministic variance map removes that purely
numerical modulation.  Because every latent mode uses the same spatial
correlation, the same scalar correction restores the complete Noll covariance,
not only the diagonal variances.

Array convention matches ``Kolmogorov.coeffs``: index 0 is Noll j=2,
index 1 is j=3, ..., index 229 is j=231.  Piston is omitted.
"""

from functools import lru_cache

import numpy as np
import scipy.fft as sfft
from scipy.integrate import quad
from scipy.special import jv

from .wavefront import K_MODES, noll_cov

TILT_CORR_HALF_PX = 55.0
# Numerical sampling density only.  It is not a turbulence parameter.
ANCHOR_SPACING_PX = 4.0


def _bessel_int(order, s):
    return quad(
        lambda z: z ** (-14.0 / 3.0)
        * jv(order, 2.0 * s * z)
        * jv(2, z) ** 2,
        0.0,
        1e3,
        limit=2000,
    )[0]


@lru_cache(maxsize=1)
def corr_table():
    """Normalized tilt correlation C(s) used by the previous D3 geometry."""
    s = np.concatenate(
        [np.linspace(0.0, 5.0, 101), np.geomspace(5.25, 220.0, 80)]
    )
    i0 = np.array([_bessel_int(0, v) for v in s], dtype=np.float64)
    i2 = np.array([_bessel_int(2, v) for v in s], dtype=np.float64)
    c = (i0 + i2) / i0[0]
    c[0] = 1.0
    return s, c


def _cov_blocks(cov, tol=1e-14):
    """Connected sparse blocks of the Noll covariance matrix."""
    adjacency = np.abs(cov) > tol
    seen = np.zeros(len(cov), dtype=bool)
    groups = []
    for start in range(len(cov)):
        if seen[start]:
            continue
        stack = [start]
        seen[start] = True
        group = []
        while stack:
            u = stack.pop()
            group.append(u)
            for v in np.flatnonzero(adjacency[u]):
                v = int(v)
                if not seen[v]:
                    seen[v] = True
                    stack.append(v)
        groups.append(np.asarray(sorted(group), dtype=np.intp))
    return groups


def _rfft_full_sum(a):
    """Sum a real-even spectrum represented by rfft2 over the full FFT."""
    if a.shape[-1] == 1:
        return float(a[..., 0].sum())
    # For even FFT length, first and last rfft columns are self-conjugate.
    return float(a[..., 0].sum() + a[..., -1].sum() + 2.0 * a[..., 1:-1].sum())


def _bilinear_resize(x, n):
    """Resize (C,g,g) -> (C,n,n) by bilinear interpolation."""
    x = np.asarray(x, dtype=np.float32)
    c, g, g2 = x.shape
    if g != g2:
        raise ValueError("anchor field must be square")
    n = int(n)
    if g == n:
        return x
    if g == 1:
        return np.broadcast_to(x, (c, n, n)).astype(np.float32, copy=True)

    q = np.linspace(0.0, g - 1.0, n, dtype=np.float32)
    i0 = np.floor(q).astype(np.intp)
    i1 = np.minimum(i0 + 1, g - 1)
    t = q - i0

    y = x[:, i0, :] * (1.0 - t)[None, :, None] + x[:, i1, :] * t[None, :, None]
    return (
        y[:, :, i0] * (1.0 - t)[None, None, :]
        + y[:, :, i1] * t[None, None, :]
    ).astype(np.float32, copy=False)


class DenseZernikeSampler:
    """Stationary FFT sampler for modes j=2..K with D2/Noll marginals."""

    def __init__(
        self,
        k_modes=K_MODES,
        corr_half_px=TILT_CORR_HALF_PX,
        anchor_spacing_px=ANCHOR_SPACING_PX,
    ):
        self.k_modes = int(k_modes)
        self.corr_half_px = float(corr_half_px)
        self.anchor_spacing_px = float(anchor_spacing_px)
        if self.k_modes != K_MODES:
            raise ValueError(f"D3 is fixed at K_MODES={K_MODES}")
        if self.corr_half_px <= 0.0 or self.anchor_spacing_px <= 0.0:
            raise ValueError("spatial scales must be positive")

        # Exactly the same point covariance as D2, piston removed.
        self.cov = noll_cov(self.k_modes)[1:, 1:].astype(np.float64, copy=False)
        self.groups = _cov_blocks(self.cov)
        self.block_roots = []
        for idx in self.groups:
            sub = self.cov[np.ix_(idx, idx)]
            self.block_roots.append(np.linalg.cholesky(sub).astype(np.float32))

        self.s_tab, self.c_tab = corr_table()
        s_half = np.interp(0.5, self.c_tab[::-1], self.s_tab[::-1])
        self.px_per_s = self.corr_half_px / float(s_half)

        self._geom_cache = {}
        self._root_cache = {}
        self._var_cache = {}

    @property
    def n_coeff(self):
        return self.k_modes - 1

    def modal_covariance_from_roots(self):
        """Reconstruct C_Noll from the block Cholesky factors."""
        out = np.zeros_like(self.cov)
        for idx, root in zip(self.groups, self.block_roots):
            rr = root.astype(np.float64)
            out[np.ix_(idx, idx)] = rr @ rr.T
        return out

    def _geometry(self, n):
        n = int(n)
        cached = self._geom_cache.get(n)
        if cached is not None:
            return cached
        if n <= 1:
            g, step = 1, 1.0
        else:
            g = int(np.ceil((n - 1) / self.anchor_spacing_px)) + 1
            g = max(2, min(g, n))
            step = (n - 1) / (g - 1)
        self._geom_cache[n] = (g, float(step))
        return self._geom_cache[n]

    def _embed_size(self, n):
        """FFT-friendly circulant embedding size, always >= 2*g and even."""
        g, _ = self._geometry(n)
        return 2 * int(sfft.next_fast_len(g))

    def _spectrum_root(self, n):
        """Root spectrum of the unit-variance stationary latent field."""
        n = int(n)
        cached = self._root_cache.get(n)
        if cached is not None:
            return cached
        g, step = self._geometry(n)
        m = self._embed_size(n)
        lag = np.minimum(np.arange(m), m - np.arange(m)).astype(np.float64)
        radius_px = np.hypot(lag[:, None], lag[None, :]) * step
        cov = np.interp(
            radius_px / self.px_per_s,
            self.s_tab,
            self.c_tab,
            left=1.0,
            right=float(self.c_tab[-1]),
        )
        lam = np.maximum(sfft.rfft2(cov).real, 0.0)
        total = _rfft_full_sum(lam)
        if not np.isfinite(total) or total <= 0.0:
            raise RuntimeError("invalid D3 spatial spectrum")
        # numpy/scipy irfft2 divides by m^2, hence this normalization gives
        # exactly unit variance at every anchor point.
        root = np.sqrt(lam * (m * m / total)).astype(np.float32)
        self._root_cache[n] = root
        return root

    def embedded_corr(self, n):
        """Autocorrelation represented by the FFT embedding, for tests."""
        g, _ = self._geometry(n)
        m = self._embed_size(n)
        root = self._spectrum_root(n).astype(np.float64)
        cov = sfft.irfft2(root * root, s=(m, m)).real
        return cov / cov[0, 0]

    def _interp_variance(self, n):
        """Variance map produced by bilinear interpolation of a unit field."""
        n = int(n)
        cached = self._var_cache.get(n)
        if cached is not None:
            return cached
        g, _ = self._geometry(n)
        if g == n:
            v = np.ones((n, n), dtype=np.float32)
            self._var_cache[n] = v
            return v

        m = self._embed_size(n)
        root = self._spectrum_root(n).astype(np.float64)
        cov = sfft.irfft2(root * root, s=(m, m)).real
        c00 = float(cov[0, 0])
        cx = float(cov[0, 1] / c00)
        cy = float(cov[1, 0] / c00)
        cpp = float(cov[1, 1] / c00)
        cpm = float(cov[1, -1] / c00)

        q = np.linspace(0.0, g - 1.0, n, dtype=np.float64)
        f = q - np.floor(q)
        a = 1.0 - f
        b = f
        w00 = a[:, None] * a[None, :]
        w01 = a[:, None] * b[None, :]
        w10 = b[:, None] * a[None, :]
        w11 = b[:, None] * b[None, :]

        v = w00*w00 + w01*w01 + w10*w10 + w11*w11
        v += 2.0 * cx * (w00*w01 + w10*w11)
        v += 2.0 * cy * (w00*w10 + w01*w11)
        v += 2.0 * cpp * (w00*w11)
        v += 2.0 * cpm * (w01*w10)
        v = np.maximum(v, 1e-6).astype(np.float32)
        self._var_cache[n] = v
        return v

    def _draw_mixed_coarse(self, n, rng):
        """Draw the joint Noll field only on the internal FFT grid.

        This is the same latent Gaussian construction as ``sample`` but all
        spatial interpolation is postponed until we know which outputs D3
        actually needs.  White noise is still drawn block-by-block in the
        same order as before; FFTs are batched only for speed.
        """
        n = int(n)
        g, _ = self._geometry(n)
        m = self._embed_size(n)
        spectral_root = self._spectrum_root(n)

        # Keep the historical RNG consumption/order exactly: each covariance
        # block gets its own standard_normal call.  The only optimization is
        # that the 2-D FFT itself is executed as one batched transform.
        white = np.empty((self.n_coeff, m, m), dtype=np.float32)
        spans = []
        off = 0
        for idx in self.groups:
            b = len(idx)
            white[off:off + b] = rng.standard_normal((b, m, m), dtype=np.float32)
            spans.append((idx, slice(off, off + b)))
            off += b

        spec = sfft.rfft2(white, axes=(-2, -1)) * spectral_root[None, :, :]
        latent = sfft.irfft2(spec, s=(m, m), axes=(-2, -1))[:, :g, :g]
        latent = latent.astype(np.float32, copy=False)

        mixed = np.empty((self.n_coeff, g, g), dtype=np.float32)
        for (idx, sl), modal_root in zip(spans, self.block_roots):
            b = len(idx)
            mixed[idx] = (modal_root @ latent[sl].reshape(b, -1)).reshape(b, g, g)
        return mixed

    def _sample_regular_via_dense(self, coarse, n, out_g):
        """Match ``_bilinear_resize(..., n)`` + variance correction +
        regular sampling, without materializing the full dense coefficient
        stack.

        Only the dense pixels touched by the final ``out_g x out_g`` anchor
        grid are evaluated.  This is algebraically the same linear operation
        used by the old D3 path.
        """
        coarse = np.asarray(coarse, dtype=np.float32)
        c, g, g2 = coarse.shape
        n, out_g = int(n), int(out_g)
        if g != g2 or n < 2 or out_g < 2:
            raise ValueError('invalid coarse/dense sampling geometry')

        qd = np.linspace(0.0, n - 1.0, out_g, dtype=np.float32)
        d0 = np.floor(qd).astype(np.intp)
        d1 = np.minimum(d0 + 1, n - 1)
        td = qd - d0
        ids = np.unique(np.concatenate([d0, d1]))

        # Evaluate the original coarse->dense bilinear interpolation only at
        # the dense rows/columns that the subsequent anchor sampler touches.
        qc = ids.astype(np.float32) * np.float32((g - 1) / (n - 1))
        c0 = np.floor(qc).astype(np.intp)
        c1 = np.minimum(c0 + 1, g - 1)
        tc = qc - c0
        y = (coarse[:, c0, :] * (1.0 - tc)[None, :, None]
             + coarse[:, c1, :] * tc[None, :, None])
        sub = (y[:, :, c0] * (1.0 - tc)[None, None, :]
               + y[:, :, c1] * tc[None, None, :])

        inv_std = 1.0 / np.sqrt(self._interp_variance(n))
        sub *= inv_std[np.ix_(ids, ids)][None, :, :]

        p0 = np.searchsorted(ids, d0)
        p1 = np.searchsorted(ids, d1)
        yy = sub[:, p0, :] * (1.0 - td)[None, :, None] + sub[:, p1, :] * td[None, :, None]
        return (
            yy[:, :, p0] * (1.0 - td)[None, None, :]
            + yy[:, :, p1] * td[None, None, :]
        ).astype(np.float32, copy=False)

    def sample_for_d3(self, n, d_over_r0, rng, high_grid):
        """Draw exactly the coefficient data consumed by D3.

        Returns ``(tilt_dense, high_anchor)`` where ``tilt_dense`` has shape
        ``(2,n,n)`` for j=2,3 and ``high_anchor`` has shape
        ``(K-3, high_grid, high_grid)`` for j=4..K.  Relative to constructing
        all 230 dense planes first, this removes the large temporary array but
        preserves the same Gaussian/Noll realization and the same numerical
        interpolation at the PSF anchor locations.
        """
        n = int(n)
        dr = float(d_over_r0)
        high_grid = int(high_grid)
        if n <= 0:
            raise ValueError('n must be positive')
        if high_grid < 2:
            raise ValueError('high_grid must be >= 2')
        if not np.isfinite(dr) or dr <= 0.0:
            raise ValueError('d_over_r0 must be positive and finite')

        coarse = self._draw_mixed_coarse(n, rng)
        scale = np.float32(dr ** (5.0 / 6.0))

        tilt = _bilinear_resize(coarse[:2], n)
        tilt *= (1.0 / np.sqrt(self._interp_variance(n)))[None, :, :]
        tilt *= scale

        high = self._sample_regular_via_dense(coarse[2:], n, high_grid)
        high *= scale
        return tilt.astype(np.float32, copy=False), high.astype(np.float32, copy=False)

    def sample(self, n, d_over_r0, rng):
        """Draw all dense coefficients with pointwise D2/Noll covariance.

        This full-field API is retained for diagnostics/tests.  Production D3
        uses ``sample_for_d3`` so high-order modes are never materialized at
        pixels where no PSF is evaluated.
        """
        n = int(n)
        dr = float(d_over_r0)
        if n <= 0:
            raise ValueError('n must be positive')
        if not np.isfinite(dr) or dr <= 0.0:
            raise ValueError('d_over_r0 must be positive and finite')

        coarse = self._draw_mixed_coarse(n, rng)
        out = _bilinear_resize(coarse, n)
        out *= (1.0 / np.sqrt(self._interp_variance(n)))[None, :, :]
        out *= np.float32(dr ** (5.0 / 6.0))
        return out.astype(np.float32, copy=False)

